[project]
name = "setup_codespaces"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
pandas = "2.1.1.*"
matplotlib = "3.8.0.*"
ipykernel = "6.25.2.*"
scipy = "1.11.3.*"
